production: &default
  adapter:  postgresql
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  encoding: unicode
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: salah_test
