name: Release

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /root/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ahmadshoh/salah:latest .
        working-directory: .

      - name: Tag Docker image with release version
        run: |
          DOCKER_TAG=$(echo "${GITHUB_REF}" | sed -e 's/refs\/tags\///')
          docker tag ahmadshoh/salah:latest ahmadshoh/salah:${DOCKER_TAG}
          docker tag ahmadshoh/salah:latest ahmadshoh/salah:latest

      - name: Push Docker image
        run: |
          DOCKER_TAG=$(echo "${GITHUB_REF}" | sed -e 's/refs\/tags\///')
          docker push ahmadshoh/salah:${DOCKER_TAG}
          docker push ahmadshoh/salah:latest
